import { Routes } from '@angular/router';
import { LoginComponent } from './features/login/login.component';
import { RegistroComponent } from './features/registro/registro.component';
import { DashboardComponent } from './features/dashboard/dashboard.component';
import { CadastroRestauranteComponent } from './features/restaurante/cadastro-restaurante/cadastro-restaurante.component';
import { ListaRestaurantesComponent } from './features/restaurante/lista-restaurante/lista-restaurante.component';
import { CadastroCategoriaComponent } from './features/categoria/cadastro-categoria/cadastro-categoria.component';
import { CadastroItemComponent } from './features/item/cadastro-item/cadastro-item.component';
import { ListaItemComponent } from './features/item/lista-item/lista-item.component';
import { CadastroVariacaoComponent } from './features/variacao/cadastro-variacao/cadastro-variacao.component';
import { ListaVariacaoComponent } from './features/variacao/lista-variacao/lista-variacao.component';
import { CadastroMesaComponent } from './features/mesa/cadastro-mesa/cadastro-mesa.component';
import { ListaMesaComponent } from './features/mesa/lista-mesa/lista-mesa.component';
import { CadastroClienteComponent } from './features/cadastro-cliente/cadastro-cliente.component';
import { PedidoComponent } from './features/pedido/pedido.component';
import { VariacaoComponent } from './features/variacao/variacao-pedido/variacao.component';
import { ListaPedidoComponent } from './features/pedido/lista-pedidos/lista-pedido.component';
import { RegistroFuncionarioComponent } from './features/registro/registro-funcionario/registro-funcionario.component';
import { ListaPedidoChefComponent } from './features/pedido/lista-pedidos-chef/lista-pedido-chef.component';
import { ListaPedidoGarconComponent } from './features/pedido/lista-pedidos-garcon/lista-pedido-garcon.component';

export const routes: Routes = [
  { path: 'login', component: LoginComponent },
  { path: 'registro', component: RegistroComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'cadastro-restaurante', component: CadastroRestauranteComponent },
  { path: 'lista-restaurantes', component: ListaRestaurantesComponent },
  { path: 'cadastro-categoria/:idRestaurante', component: CadastroCategoriaComponent },
  { path: 'cadastro-item/:idCategoria', component: CadastroItemComponent },
  { path: 'lista-item/:idCategoria', component: ListaItemComponent },
  { path: 'cadastro-variacao/:idItem', component: CadastroVariacaoComponent },
  { path: 'lista-variacao/:idItem', component: ListaVariacaoComponent },
  { path: 'cadastro-mesa/:idRestaurante', component: CadastroMesaComponent },
  { path: 'lista-mesa/:idRestaurante', component: ListaMesaComponent },
  { path: 'cadastro-cliente/:idMesa', component: CadastroClienteComponent },
  { path: 'pedido/:idCliente', component: PedidoComponent },
  { path: 'pedido/variacoes/:idItem', component: VariacaoComponent },
  { path: 'pedido/variacoes/:idItem/:idCliente', component: VariacaoComponent },
  { path: 'lista-pedido/:idRestaurante', component: ListaPedidoComponent },
  { path: 'cadastro-funcionario/:idRestaurante', component: RegistroFuncionarioComponent },
  { path: 'listar-pedidos-chef/:idRestaurante', component: ListaPedidoChefComponent },
  { path: 'listar-pedidos-garcon/:idRestaurante', component: ListaPedidoGarconComponent },
  { path: '', redirectTo: '/login', pathMatch: 'full' },
  { path: '**', redirectTo: '/login' }
];
